- name: Check if teleport is installed.
  stat: "path=/usr/local/bin/teleport"
  register: teleport_bin

- name: Unarchive teleport.
  unarchive:
    src: "{{ teleport_url }}"
    dest: /tmp
    remote_src: yes
  when: not teleport_bin.stat.exists

- name: Install teleport.
  command: >
    ./install
    chdir=/tmp/teleport
  become: yes
  when: not teleport_bin.stat.exists

- name: Create teleport config.
  template:
    src: "teleport.yaml.j2"
    dest: "{{ teleport_config_path }}"
    lstrip_blocks: yes
    owner: "root"
    group: "root"
    mode: 0600
  notify: reload teleport

- name: Create teleport service (systemd).
  template:
    src: "teleport.service.j2"
    dest: "/etc/systemd/system/teleport.service"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_installed

- name: Ensure teleport has selected state and enabled on boot.
  systemd:
    name: 'teleport'
    state: 'started'
    enabled: yes
    daemon_reload: "{{ service_installed.changed }}"
