---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - lint
    - verify
verifier:
  name: ansible
